import sys
import os
import openpyxl
import xml.etree.ElementTree as ET

import _config
import _constants
import xml_utils

def run():
    source = os.path.join(_config.DATA_TEXTS_PATH, 'Strings.xlsx')
    output = os.path.join(_config.DATA_VALUES_PATH, 'strings.xml')
    
    book = openpyxl.load_workbook(source, data_only = True)
    
    xml_root = ET.Element(None)
    xml_root.append(ET.Comment(_constants.STR_AUTOGENERATED))
    
    xml_res = ET.SubElement(xml_root, 'resources')

    for sheet in book.worksheets:
        title = sheet.cell(1, 3).value
        prefix = sheet.cell(2, 3).value
        count = sheet.cell(3, 3).value
        
        xml_res.append(ET.Comment(title))
        
        if prefix:
            prefix = prefix + '_'
        else:
            prefix = ''
        
        for row in sheet.iter_rows(min_row = 5, max_row = 5 + int(count - 1), min_col = 3, max_col = 4):
            row = [cell.value for cell in row]
            full_name = prefix + row[0]
            value = row[1].replace("'", "\\'")
            
            xml_string = ET.SubElement(xml_res, 'string')
            xml_string.set('name', full_name)
            xml_string.text = value
            
    ET.indent(xml_root)
    ET.ElementTree(xml_root).write(output, encoding = 'unicode')